services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    container_name: bot
    image: sjeinok/max_express_bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - HELP_1688=${HELP_1688}
      - HELP_PINDUODUO=${HELP_PINDUODUO}
      - HELP_POIZON=${HELP_POIZON}
      - HELP_TAOBAO=${HELP_TAOBAO}
      - SQLX_OFFLINE=true
    depends_on:
      - db
    ports:
      - '8080:8080'

volumes:
  pgdata: {}
